use std::fmt::Write as FmtWrite;
use std::fs;
use crate::config::Config;
use crate::detect::Env;
use crate::graph::BuildGraph;
use crate::error::BearError;

pub fn write(cfg: &Config, env: &Env, graph: &BuildGraph) -> Result<(), BearError> {
    fs::create_dir_all("build").map_err(|e| BearError::Emit(format!("could not create build/ directory: {}", e)))?;

    let mut out = String::new();

    write_header(cfg, env, &mut out);
    write_rules(&mut out);
    write_compile_edges(cfg, env, graph, &mut out)?;
    write_link_edge(cfg, env, graph, &mut out);

    fs::write("build.ninja", &out).map_err(|e| BearError::Emit(format!("could not write build.ninja: {}", e)))?;

    Ok(())
}

fn write_header(cfg: &Config, env: &Env, out: &mut String) {
    writeln!(out, "# generated by bearbuild - do not edit by hand").unwrap();
    writeln!(out, "# project: {} v{}", cfg.project.name, cfg.project.version).unwrap();
    writeln!(out, "# compiler: {}", env.compiler_ver).unwrap();
    writeln!(out).unwrap();

    writeln!(out, "cc = {}", env.compiler).unwrap();

    let mut cflags = Vec::new();
    cflags.push(format!("-std={}", cfg.build.std));

    for inc in &cfg.build.includes {
        cflags.push(format!("-I{}", inc));
    }

    for flag in &cfg.build.flags {
        cflags.push(flag.clone());
    }

    for flag in &env.pkg_cflags {
        cflags.push(flag.clone());
    }

    writeln!(out, "cflags = {}", cflags.join(" ")).unwrap();

    if !env.pkg_libs.is_empty() {
        writeln!(out, "libs = {}", env.pkg_libs.join(" ")).unwrap();
    } else {
        writeln!(out, "libs =").unwrap();
    }

    writeln!(out).unwrap();
}


fn write_rules(out: &mut String) {
    writeln!(out, "rule cc").unwrap();
    writeln!(out, " command = $cc $cflags -MMD -MF $out.d -c $in -o $out").unwrap();
    writeln!(out, " depfile = $out.d").unwrap();
    writeln!(out, " deps = gcc").unwrap();
    writeln!(out).unwrap();

    writeln!(out, "rule link").unwrap();
    writeln!(out, " command = $cc $in $libs -o #out").unwrap();
    writeln!(out).unwrap();
}

fn write_compile_edges(
    _cfg: &Config,
    _env: &Env,
    graph: &BuildGraph,
    out: &mut String,
) -> Resul<(), BearError> {
    writeln!(out, "# compile").unwrap();

    for sf in &graph.sources {
        let src = sf.src.display();
        let obj = sf.obj.display();

        writeln!(out, "build {}: cc {}", obj, src).unwrap();
    }

    writeln!(out).unwrap();
    Ok(())
}



